# -*- coding: utf-8 -*-
"""Streamlit_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Nfn_YaOBhGPvDyKqltl22lMjAMfmoua
"""

!pip install streamlit
!streamlit run streamlit_app.py

# streamlit_app.py
import streamlit as st
import joblib
import numpy as np
import hashlib

MODEL_PATH = "Product_Rec.pkl"

@st.cache_resource
def load_model(path=MODEL_PATH):
    return joblib.load(path)

def deterministic_str_to_num(s: str, mod: int = 10000) -> float:
    """Convert a string deterministically to a numeric value (fallback for categorical text).
    Uses md5 hash to ensure stable mapping across runs."""
    if s is None:
        return 0.0
    s = str(s).strip()
    try:
        return float(s)
    except Exception:
        h = hashlib.md5(s.encode("utf-8")).hexdigest()
        return float(int(h, 16) % mod)

def build_feature_array(user_id, product_id, product_name, category, price, brand, tags, rating):
    """Return a 2D numpy array shaped (1,8) in the same column order used during training:
    ['User id ', 'Product id', 'Product Name', 'Category', 'Price', 'Brand', 'Tags', 'Rating']"""
    # Convert numeric-like strings; fallback map categorical text to deterministic numbers
    f_user = deterministic_str_to_num(user_id)
    f_prod = deterministic_str_to_num(product_id)
    f_pname = deterministic_str_to_num(product_name)
    f_cat = deterministic_str_to_num(category)
    try:
        f_price = float(price)
    except Exception:
        f_price = deterministic_str_to_num(price)
    f_brand = deterministic_str_to_num(brand)
    f_tags = deterministic_str_to_num(tags)
    try:
        f_rating = float(rating)
    except Exception:
        f_rating = deterministic_str_to_num(rating)
    arr = np.array([[f_user, f_prod, f_pname, f_cat, f_price, f_brand, f_tags, f_rating]], dtype=float)
    return arr

def main():
    st.title("Product Recommendation Prediction Model")

    # Load model (always from default path)
    try:
        model = load_model(MODEL_PATH)
    except Exception as e:
        st.error(f"Failed to load model from {MODEL_PATH}: {e}")
        return

    # Input fields
    user_id = st.text_input("User id", value="")
    product_id = st.text_input("Product id", value="")
    product_name = st.text_input("Product Name", value="")
    category = st.text_input("Category", value="")
    price = st.number_input("Price", value=0.0, format="%.2f")
    brand = st.text_input("Brand", value="")
    tags = st.text_input("Tags", value="")
    rating = st.number_input("Rating", value=0.0, format="%.2f")

    if st.button("Predict"):
        X = build_feature_array(user_id, product_id, product_name, category, price, brand, tags, rating)
        try:
            pred = model.predict(X)
            # If predict returns array-like, extract first element
            if hasattr(pred, "__len__"):
                out = pred[0]
            else:
                out = pred
            st.write("Interaction Type")
            st.write(out)
        except Exception as e:
            st.error(f"Prediction failed: {e}")

if __name__ == "__main__":
    main()